apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: clinic-cpo
  name: klinik-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klinik-web
  template:
    metadata:
      labels:
        app: klinik-web
    spec:
      containers:
      - name: web
        image: docker.io/youlong255/klinik:latest
        ports:
        - containerPort: 80