apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: clinic-cpo
  name: klinik-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-cpo
  template:
    metadata:
      labels:
        app: clinic-cpo
    spec:
      containers:
      - name: web
        image: $REGISTRY/$DOCKERHUB_USERNAME/$APP_NAME
        ports:
        - containerPort: 80